project_id = "rqdtcvvpybgjinoqwacw"

[functions.content-generator]
verify_jwt = false

[functions.quick-explainer]
verify_jwt = false

[functions.lesson-planner]
verify_jwt = false

[functions.visual-aid-creator]
verify_jwt = false

[functions.worksheet-differentiator]
verify_jwt = false

[functions.reading-assessment]
verify_jwt = false

[functions.game-generator]
verify_jwt = false